// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Porten_API;

#nullable disable

namespace Porten_API.Migrations
{
    [DbContext(typeof(WatchDbContext))]
    partial class WatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Porten_API.Watch", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            Name = "Carl von Zeyten",
                            Price = 16500m,
                            img = "img/goods/1.png"
                        },
                        new
                        {
                            Name = "JORD AR5905",
                            Price = 65000m,
                            img = "img/goods/2.png"
                        },
                        new
                        {
                            Name = "Emporio Armani Sportivo",
                            Price = 165000m,
                            img = "img/goods/3.png"
                        },
                        new
                        {
                            Name = "Rolex Oyster Perpetual",
                            Price = 280000m,
                            img = "img/goods/4.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
